rvm:
  - 2.0.0
  - 1.9.3
  - 1.8.7
  - jruby

# whitelist
branches:
  only:
    - master
    - aruba-in-process

notifications:
  email:
    - cukes-devs@googlegroups.com
  irc:
    - "irc.freenode.org#cucumber"
