# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.0

jobs:
  "ruby-2.4.1":
    docker:
       - image: circleci/ruby:2.4.1
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Run RSpec
          command: bundle exec rake spec
      - run:
          name: Run Cucumber
          command: bundle exec rake cucumber

  "ruby-2.3.5":
    docker:
       - image: circleci/ruby:2.3.5
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Run RSpec
          command: bundle exec rake spec
      - run:
          name: Run Cucumber
          command: bundle exec rake cucumber

workflows:
  version: 2
  build:
    jobs:
      - "ruby-2.4.1"
      - "ruby-2.3.5"
